language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  # - "pypy2.7"
  - "pypy3.5"

matrix:
  include:
    - os: linux
      install: pip install --editable .[dev,travis]
      script:
        - pytest tests/ --cov oscpy/ --cov-branch
        - travis_retry coveralls
    - os: osx
      language: sh
      install: pip install --editable .[dev,travis]
      script:
        - pytest tests/ --cov oscpy/ --cov-branch
        - travis_retry coveralls
    - os: windows
      language: sh
      before_install:
        - choco install python3
        - export PATH="/c/Python37/:/c/Python37/Scripts:$PATH"
      install: pip install --editable .[dev,travis]
      script:
        - pytest tests/ --cov oscpy/ --cov-branch
        - travis_retry coveralls

