on: push
name: on push
jobs:
  TestsLinux37:
    name: run tests on linux, python3.7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: prepare
      run: pip install -U setuptools wheel
    - name: install
      run: pip install .[dev]
    - name: test
      run: python -m pytest tests/ --cov oscpy/ --cov-branch
    - name: coveralls
      run: coveralls


  TestsWindows37:
    name: run tests on windows, python3.7
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      run: pip install .[dev]
    - name: test
      run: pytest
