on: push
name: on push
jobs:
  TestsLinux37:
    name: run tests on linux, python3.7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: prepare
      run: pip3.7 install -U setuptools wheel
    - name: install
      run: pip3.7 install .[dev,travis]
    - name: test
      run: python3.7 -m pytest tests/ --cov oscpy/ --cov-branch
    - name: coveralls
      run: python -m coveralls
      env: # Or as an environment variable
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  TestsWindows37:
    name: run tests on windows, python3.7
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      run: pip3.7 install .[dev]
    - name: test
      run: python3.7 -m pytest tests/

  TestsMacOs27:
    name: run tests on osx, python2.7
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      run: pip install .[dev]
    - name: test
      run: pytest
